'use strict';
let viewMode='month',analysisCategory='',analysisSub='전체',analysisMonth='',analysisScope='';const baseRender=render;
function rangeRows(){const year=$('year').value,half=Number($('half').value);return records.filter(r=>r.date.startsWith(year+'-')&&(viewMode!=='half'||(Number(r.date.slice(5,7))<=6?1:2)===half));}
render=function(){baseRender();document.querySelector('.lists').hidden=viewMode!=='month';document.querySelector('.analysis').hidden=viewMode!=='month';$('periodAnalysis').hidden=viewMode==='month';$('half').hidden=viewMode!=='half';$('month').parentElement.hidden=viewMode!=='month';const m=statusFor(period());$('monthStatus').textContent=viewMode==='month'?(m.confirmed?'확정':m.uploaded.length===2?'수정 중':m.uploaded.length?m.uploaded.includes('토끼')?'캥거루 업로드 대기':'토끼 업로드 대기':'미등록'):'';$('reopen').hidden=viewMode!=='month'||!m.confirmed;$('save').textContent=viewMode==='month'&&m.uploaded.length===2&&!m.confirmed?'다시 확정':'저장';document.querySelector('.summary>strong').textContent=viewMode==='month'?'이번 달 가계 현황':viewMode==='year'?$('year').value+'년 가계 현황':$('year').value+'년 '+($('half').value==='1'?'상반기':'하반기');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===viewMode));let diff=$('difference');if(!diff){diff=document.createElement('span');diff.id='difference';document.querySelector('.summary').insertBefore(diff,$('savedState'))}const rs=viewMode==='month'?current():rangeRows(),income=sum(rs.filter(r=>r.type==='수입')),expense=sum(rs.filter(r=>r.type==='지출'));$('incomeTotal').textContent=money(income);$('expenseTotal').textContent=money(expense);diff.textContent='차액 '+money(income-expense);if(viewMode!=='month')renderPeriod(rs);};
function renderPeriod(rs){const months=viewMode==='year'?Array.from({length:12},(_,i)=>i+1):Array.from({length:6},(_,i)=>i+($('half').value==='1'?1:7)),data=months.map(m=>{const key=$('year').value+'-'+String(m).padStart(2,'0'),rows=rs.filter(r=>r.date.startsWith(key));return {m,key,income:sum(rows.filter(r=>r.type==='수입')),expense:sum(rows.filter(r=>r.type==='지출')),registered:statusFor(key).uploaded.length>0,confirmed:statusFor(key).confirmed}});const max=Math.max(...data.flatMap(d=>[d.income,d.expense]),1),min=Math.min(...data.flatMap(d=>[d.income,d.expense]),0),width=1000,height=300,x=i=>70+i*(850/Math.max(1,data.length-1)),y=a=>250-(a-min)/(max-min)*200;const path=type=>{let s='',open=false;data.forEach((d,i)=>{if(!d.registered){open=false;return}s+=(open?' L':' M')+x(i)+','+y(d[type]);open=true});return s};const grid=Array.from({length:5},(_,i)=>{const a=min+(max-min)*i/4,yy=y(a);return `<line x1="70" x2="940" y1="${yy}" y2="${yy}" stroke="#e3e7de"/><text x="60" y="${yy+5}" text-anchor="end" font-size="13">${Math.round(a/10000)}만</text>`}).join('');const points=data.map((d,i)=>d.registered?`<circle cx="${x(i)}" cy="${y(d.income)}" r="5" fill="#547457"/><circle cx="${x(i)}" cy="${y(d.expense)}" r="5" fill="#a184be"/>`:'').join('');$('periodAnalysis').innerHTML=`<h2>월별 수입과 지출</h2><p class="hint"><span class="legend-income">● 수입</span> <span class="legend-expense">● 지출</span> · 월에 마우스를 올리거나 누르면 합계를 볼 수 있어요.</p><div class="trend"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="월별 수입과 지출 추이">${grid}<path d="${path('income')}" fill="none" stroke="#547457" stroke-width="3"/><path d="${path('expense')}" fill="none" stroke="#a184be" stroke-width="3"/>${points}${data.map((d,i)=>`<text x="${x(i)}" y="280" text-anchor="middle" font-size="15">${d.m}월</text>`).join('')}</svg><div class="trend-hit">${data.map(d=>`<button data-trend="${d.key}" aria-label="${d.m}월 수입 ${money(d.income)}, 지출 ${money(d.expense)}">${d.m}월</button>`).join('')}</div></div><div id="trendInfo" class="trend-info">등록한 월을 선택하면 수입·지출·차액이 표시됩니다.</div><h2 class="pie-heading">기간별 지출 비중</h2><div id="pieArea"></div><div id="periodDetails"></div>`;const show=key=>{const d=data.find(d=>d.key===key);$('trendInfo').textContent=d.registered?`${d.m}월 · ${d.confirmed?'확정':'업로드 대기 또는 수정 중'} | 수입 ${money(d.income)} · 지출 ${money(d.expense)} · 차액 ${money(d.income-d.expense)}`:`${d.m}월 · 미등록`};document.querySelectorAll('[data-trend]').forEach(b=>{b.onmouseenter=b.onfocus=b.onclick=()=>show(b.dataset.trend)});renderPie(rs);}
function renderPie(rs){const groups=Object.entries(Object.groupBy(rs.filter(r=>r.type==='지출'),r=>r.category)).map(([c,rows])=>[c,sum(rows)]).sort((a,b)=>b[1]-a[1]);const positive=groups.filter(g=>g[1]>0),total=sum(positive.map(g=>({amount:g[1]}))),colors=['#b49acc','#8faa7f','#9dbbd4','#e5b48f','#cfb9a3','#92bfb5','#e3a9ba','#c7c88f','#b5bac4','#9fa2cc'];let cursor=0;const gradient=positive.map(([c,a],i)=>{const start=cursor;cursor+=a/total*100;return `${colors[i%colors.length]} ${start}% ${cursor}%`}).join(',');$('pieArea').innerHTML=groups.length?`<div class="pie-layout"><div class="donut" style="background:conic-gradient(${gradient||'#eee 0% 100%'})" role="img" aria-label="기간별 카테고리 지출 비중"><span>${money(sum(groups.map(g=>({amount:g[1]}))))}<small>총지출</small></span><svg class="pie-targets" viewBox="0 0 100 100">${positive.map(([c,a],i)=>{const start=positive.slice(0,i).reduce((n,g)=>n+g[1]/total*360,0),end=start+a/total*360,pt=angle=>[50+49*Math.sin(angle*Math.PI/180),50-49*Math.cos(angle*Math.PI/180)],p1=pt(start),p2=pt(Math.min(end,start+359.999));return `<path data-pie="${escapeHtml(c)}" d="M50,50 L${p1.join(',')} A49,49 0 ${end-start>180?1:0},1 ${p2.join(',')} Z" fill="transparent"><title>${escapeHtml(c)} ${money(a)}</title></path>`}).join('')}</svg></div><div class="pie-legend">${groups.map(([c,a],i)=>`<button data-pie="${escapeHtml(c)}"><i style="background:${colors[i%colors.length]}"></i><strong>${escapeHtml(c)}</strong><span>${money(a)}</span></button>`).join('')}</div></div><p class="hint">분류를 누르면 월별 합계를 볼 수 있어요.${groups.some(g=>g[1]<0)?' 음수 합계는 원그래프 조각에서 제외하고 목록에 표시합니다.':''}</p>`:'<div class="empty">아직 등록된 지출이 없어요.</div>';renderPeriodDetails(rs);}
function renderPeriodDetails(rs){
const scope=$('year').value+'-'+viewMode+'-'+$('half').value;
if(analysisScope!==scope){analysisMonth='';analysisSub='전체';analysisScope=scope;}
const rows=rs.filter(r=>r.type==='지출'&&r.category===analysisCategory);if(!rows.length){$('periodDetails').innerHTML='';return}const months=Object.entries(Object.groupBy(rows,r=>r.date.slice(0,7))).sort(([a],[b])=>a.localeCompare(b));
if(!months.some(([key])=>key===analysisMonth))analysisMonth='';
const heading=`<div class="detail-title"><strong>${escapeHtml(analysisCategory)} 월별 합계</strong></div>`;
const monthList=`<div class="pie-legend">${months.map(([key,items])=>`<button data-period-month="${key}" aria-expanded="${key===analysisMonth}" style="${key===analysisMonth?'background:#edf2e8':''}"><strong>${Number(key.slice(5))}월</strong><span>${money(sum(items))} · ${items.length}건</span></button>`).join('')}</div><p class="hint">월을 누르면 해당 월의 날짜별 지출 내역이 펼쳐져요.</p>`;
if(!analysisMonth){$('periodDetails').innerHTML=heading+monthList;return;}
const monthRows=rows.filter(r=>r.date.startsWith(analysisMonth+'-'));
const subs=['전체',...new Set(monthRows.map(r=>r.subcategory||'미분류'))];
if(!subs.includes(analysisSub))analysisSub='전체';
$('periodDetails').innerHTML=heading+monthList+`<div class="detail-title"><strong>${Number(analysisMonth.slice(5))}월 · ${escapeHtml(analysisCategory)} 날짜별 내역</strong><div class="chips">${subs.map(s=>`<button data-period-sub="${escapeHtml(s)}" class="${s===analysisSub?'active':''}">${escapeHtml(s)}</button>`).join('')}</div></div>`+table(monthRows.filter(r=>analysisSub==='전체'||(r.subcategory||'미분류')===analysisSub).sort((a,b)=>b.date.localeCompare(a.date)));
}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]'),p=e.target.closest('[data-pie]'),s=e.target.closest('[data-period-sub]'),m=e.target.closest('[data-period-month]');if(v){viewMode=v.dataset.view;analysisCategory='';analysisMonth='';render()}if(p){analysisCategory=p.dataset.pie;analysisSub='전체';analysisMonth='';renderPeriodDetails(rangeRows());$('periodDetails').scrollIntoView({behavior:'smooth',block:'nearest'})}if(m){analysisMonth=analysisMonth===m.dataset.periodMonth?'':m.dataset.periodMonth;analysisSub='전체';renderPeriodDetails(rangeRows())}if(s){analysisSub=s.dataset.periodSub;renderPeriodDetails(rangeRows())}});$('half').onchange=()=>render();
$('half').value=Number($('month').value)>6?'2':'1';
render();initShared();
