'use strict';
const $=id=>document.getElementById(id), STORAGE='momo-ledger-v1', money=v=>new Intl.NumberFormat('ko-KR').format(v)+'원', escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[], pending=[], editing=null, expanded=false, selectedCategory='', selectedSub='전체';
try{records=validateRecords(JSON.parse(localStorage.getItem(STORAGE)||'[]'))}catch{ $('notice').textContent='저장된 내역을 읽지 못했어요. 백업 파일로 복원하세요.'; }
const today=new Date();for(let y=2020;y<=Math.max(2040,today.getFullYear()+10);y++)$('year').add(new Option(y+'년',y));for(let m=1;m<=12;m++)$('month').add(new Option(m+'월',m));$('year').value=today.getFullYear();$('month').value=today.getMonth()+1;
function period(){return $('year').value+'-'+String($('month').value).padStart(2,'0')}
function validateRecords(rs){if(!Array.isArray(rs))throw Error('내역 형식이 올바르지 않습니다.');return rs.map(r=>{if(!r||!['토끼','캥거루'].includes(r.owner)||!['수입','지출'].includes(r.type)||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!Number.isFinite(r.amount))throw Error('내역 형식이 올바르지 않습니다.');return {id:r.id||crypto.randomUUID(),owner:r.owner,type:r.type,date:r.date,category:String(r.category||'미분류'),subcategory:String(r.subcategory||''),description:String(r.description||''),amount:r.amount,payment:String(r.payment||''),memo:String(r.memo||'')};})}
function current(){return records.filter(r=>r.date.startsWith(period())).sort((a,b)=>b.date.localeCompare(a.date))}
function persist(message='저장했어요.'){try{localStorage.setItem(STORAGE,JSON.stringify(records));$('savedState').textContent='이 브라우저에 저장됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});$('notice').textContent=message;return true}catch{$('notice').textContent='저장 공간이 부족해 저장하지 못했어요. 백업 파일을 내려받아 주세요.';return false}}
function sum(rs){return rs.reduce((n,r)=>n+r.amount,0)}
function badge(r){return `<button class="owner ${r.owner==='토끼'?'rabbit':'kangaroo'}" data-edit="${escapeHtml(r.id)}" aria-label="${escapeHtml(r.owner+' '+r.description+' 내역 수정')}">${r.owner}</button>`}
function table(rs,expense=true){return `<div class="table-wrap"><table><thead><tr><th>날짜</th><th>${expense?'분류 · 내용':'내용'}</th><th class="money">금액</th><th class="owner-cell">입력자</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.date.slice(5).replace('-','.')}</td><td>${expense?`<strong>${escapeHtml(r.category)}${r.subcategory?' · '+escapeHtml(r.subcategory):''}</strong><span class="description">${escapeHtml(r.description)}</span>`:escapeHtml(r.description)}${r.memo?`<span class="memo">메모: ${escapeHtml(r.memo)}</span>`:''}</td><td class="money">${money(r.amount)}</td><td class="owner-cell">${badge(r)}</td></tr>`).join('')}</tbody></table></div>`}
function render(){const rs=current(),income=rs.filter(r=>r.type==='수입'),expenses=rs.filter(r=>r.type==='지출');$('incomeTotal').textContent=$('incomePanelTotal').textContent=money(sum(income));$('expenseTotal').textContent=$('expensePanelTotal').textContent=money(sum(expenses));const groups=Object.groupBy(income,r=>r.category==='급여'?'월급':r.category);$('incomeList').innerHTML=income.length?Object.entries(groups).sort((a,b)=>sum(b[1])-sum(a[1])).map(([cat,rows])=>`<div class="group"><span>${escapeHtml(cat)}</span><span>${money(sum(rows))}</span></div>${table(rows,false)}`).join(''):'<div class="empty">아직 수입 내역이 없어요.<br>정제된 엑셀 파일을 가져오세요.</div>';$('expenseList').innerHTML=expenses.length?table(expanded?expenses:expenses.slice(0,8))+(expenses.length>8?`<button class="more" id="more">${expanded?'접기':'전체 지출 '+expenses.length+'건 보기'} ▾</button>`:''):'<div class="empty">아직 지출 내역이 없어요.<br>토끼·캥거루 내역을 함께 가져올 수 있어요.</div>';if($('more'))$('more').onclick=()=>{expanded=!expanded;render()};const cats=Object.entries(Object.groupBy(expenses,r=>r.category)).map(([c,rs])=>[c,sum(rs)]).sort((a,b)=>b[1]-a[1]);const max=Math.max(...cats.map(c=>Math.abs(c[1])),1),colors=['#ceb7e2','#aac6df','#e4c7a7','#eaa8b2','#8ea67b','#afb6bc'];$('chart').innerHTML=cats.length?cats.map(([c,a],i)=>`<button class="bar-row ${c===selectedCategory?'selected':''}" data-category="${escapeHtml(c)}"><strong>${escapeHtml(c)}</strong><span class="track"><span class="bar" style="width:${Math.max(1,Math.abs(a)/max*100)}%;background:${colors[i%colors.length]}"></span></span><span class="value">${money(a)}</span></button>`).join(''):'<div class="empty">지출을 가져오면 카테고리별 금액이 표시됩니다.</div>';renderDetail(expenses);}
function renderDetail(expenses){const rows=expenses.filter(r=>r.category===selectedCategory);if(!rows.length){$('detail').innerHTML='';return}const subs=['전체',...new Set(rows.map(r=>r.subcategory||'미분류'))];if(!subs.includes(selectedSub))selectedSub='전체';$('detail').innerHTML=`<div class="detail-title"><strong>${escapeHtml(selectedCategory)} 세부 내역</strong><div class="chips">${subs.map(s=>`<button data-sub="${escapeHtml(s)}" class="${s===selectedSub?'active':''}">${escapeHtml(s)}</button>`).join('')}</div></div>`+table(rows.filter(r=>selectedSub==='전체'||(r.subcategory||'미분류')===selectedSub));}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){editing=records.find(r=>r.id===b.dataset.edit);if(!editing)return;for(const [k,v]of Object.entries(editing))if($('editForm').elements[k])$('editForm').elements[k].value=v;$('editDialog').showModal()}if(b.dataset.category){selectedCategory=b.dataset.category;selectedSub='전체';render()}if(b.dataset.sub){selectedSub=b.dataset.sub;renderDetail(current().filter(r=>r.type==='지출'))}if(b.dataset.close)$(b.dataset.close).close()});
for(const id of ['year','month'])$(id).onchange=()=>{expanded=false;selectedCategory='';render()};$('save').onclick=()=>persist();
function normalizedDate(v,y,m){let yy=y,mm=m,dd;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(!d)throw Error('날짜를 읽을 수 없습니다.');yy=d.y;mm=d.m;dd=d.d}else{const nums=String(v||'').match(/\d+/g)?.map(Number)||[];if(nums.length>=3&&nums[0]>1900){[yy,mm,dd]=nums}else if(nums.length>=2){[mm,dd]=nums}else throw Error('날짜를 읽을 수 없습니다: '+v)}const date=new Date(Date.UTC(yy,mm-1,dd));if(date.getUTCFullYear()!==yy||date.getUTCMonth()+1!==mm||date.getUTCDate()!==dd)throw Error('잘못된 날짜: '+v);if(yy!==y||mm!==m)throw Error(`파일에 선택한 ${y}년 ${m}월 밖의 날짜가 있어요: ${v}`);return `${yy}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`;}
function parseWorkbook(wb,{owner,year,month}){const out=[];for(const name of wb.SheetNames){let type='',headers=null;for(const row of XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',raw:true})){const nonempty=row.filter(v=>String(v).trim());if(nonempty.length===1&&['수입','지출'].includes(String(nonempty[0]).trim())){type=String(nonempty[0]).trim();headers=null;continue}if(row.includes('날짜')&&row.includes('금액')){headers=Object.fromEntries(row.map((v,i)=>[String(v).trim(),i]));continue}if(!headers||!type||!nonempty.length)continue;const get=k=>row[headers[k]]??'';if(!get('날짜'))continue;const amount=Number(String(get('금액')).replace(/[,\s₩원]/g,''));if(!Number.isFinite(amount)||String(get('금액')).trim()==='')throw Error('금액을 읽을 수 없습니다.');out.push({id:crypto.randomUUID(),owner,type,date:normalizedDate(get('날짜'),year,month),category:String(get('대분류')||'미분류'),subcategory:String(get('소분류')||''),description:String(get('내용')||''),amount,payment:String(get('결제수단')||''),memo:String(get('메모')||'')});}}if(!out.length)throw Error('수입·지출 구역과 날짜·금액 열이 있는 정제 파일을 선택하세요.');return out;}
$('import').onclick=()=>$('files').click();$('files').onchange=async()=>{try{if(!window.XLSX)throw Error('엑셀 기능을 불러오지 못했어요. 페이지를 새로고침해 주세요.');pending=[];for(const file of $('files').files){const filename=file.name.replace(/\.(xlsx|xls)$/i,'');const match=filename.match(/(?:^|\D)(1[0-2]|0?[1-9])\s*월?\s*(토끼|캥거루)/);const wb=XLSX.read(await file.arrayBuffer());pending.push({name:file.name,wb,month:match?Number(match[1]):Number($('month').value),owner:match?match[2]:filename.includes('캥거루')?'캥거루':'토끼'});}$('importFields').innerHTML=pending.map((p,i)=>`<div class="import-item"><strong>${escapeHtml(p.name)}</strong><div class="field-pair"><label>연도<input type="number" name="year${i}" value="${$('year').value}" min="2020" max="2100" required></label><label>월<select name="month${i}">${Array.from({length:12},(_,j)=>`<option value="${j+1}" ${j+1===p.month?'selected':''}>${j+1}월</option>`).join('')}</select></label></div><label>입력자<select name="owner${i}"><option ${p.owner==='토끼'?'selected':''}>토끼</option><option ${p.owner==='캥거루'?'selected':''}>캥거루</option></select></label></div>`).join('');$('importDialog').showModal()}catch(e){$('notice').textContent=e.message}finally{$('files').value=''}};
$('importForm').onsubmit=e=>{e.preventDefault();try{const batch=[],keys=new Set();for(let i=0;i<pending.length;i++){const form=e.target.elements,year=Number(form['year'+i].value),month=Number(form['month'+i].value),owner=form['owner'+i].value,key=`${year}-${String(month).padStart(2,'0')}|${owner}`;if(keys.has(key))throw Error('같은 월·입력자의 파일은 한 번에 하나만 가져오세요.');keys.add(key);batch.push(...parseWorkbook(pending[i].wb,{owner,year,month}));}records=records.filter(r=>!keys.has(r.date.slice(0,7)+'|'+r.owner)).concat(batch);const p=batch[0].date.split('-');if(![...$('year').options].some(o=>o.value===p[0]))$('year').add(new Option(p[0]+'년',p[0]));$('year').value=p[0];$('month').value=Number(p[1]);persist(`${pending.map(p=>p.name).join(', ')} · ${batch.length}건을 가져왔어요.`);$('importDialog').close();expanded=false;selectedCategory='';render()}catch(err){alert(err.message)}};
$('editForm').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));try{const changed=validateRecords([{...editing,...values,amount:Number(values.amount)}])[0];const before=records;records=records.map(r=>r.id===editing.id?changed:r);if(!persist('수정한 내역을 저장했어요.')){records=before;return}$('editDialog').close();render()}catch(err){alert(err.message)}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('backup').onclick=()=>download(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}),'모모네집_전체백업_'+new Date().toISOString().slice(0,10)+'.json');$('restore').onclick=()=>$('backupFile').click();$('backupFile').onchange=async()=>{try{const file=$('backupFile').files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.version!==1)throw Error('모모네 집 가계부 백업 파일이 아닙니다.');const restored=validateRecords(data.records);if(!confirm(`백업 ${restored.length}건으로 현재 브라우저의 전체 내역을 교체할까요?`))return;const old=records;records=restored;if(!persist('백업을 복원했어요.')){records=old;return}render()}catch(e){alert(e.message)}finally{$('backupFile').value=''}};
$('export').onclick=()=>{try{const rs=current();if(!rs.length)throw Error('이 달에 내보낼 내역이 없어요.');const wb=XLSX.utils.book_new(),income=rs.filter(r=>r.type==='수입'),expense=rs.filter(r=>r.type==='지출');const summary=[['모모네 집 가계부',period()],['총수입',sum(income)],['총지출',sum(expense)],[],['수입 분류','금액'],...Object.entries(Object.groupBy(income,r=>r.category==='급여'?'월급':r.category)).map(([c,r])=>[c,sum(r)]),[],['지출 분류','금액'],...Object.entries(Object.groupBy(expense,r=>r.category)).map(([c,r])=>[c,sum(r)])];const ws=XLSX.utils.aoa_to_sheet(summary);ws['!cols']=[{wch:24},{wch:20}];XLSX.utils.book_append_sheet(wb,ws,'월간 요약');for(const [name,rows]of [['수입',income],['지출',expense]]){const sheet=XLSX.utils.aoa_to_sheet([['날짜','입력자','대분류','소분류','내용','금액','결제수단','메모'],...rows.map(r=>[r.date,r.owner,r.category,r.subcategory,r.description,r.amount,r.payment,r.memo])]);sheet['!cols']=[{wch:13},{wch:10},{wch:16},{wch:16},{wch:36},{wch:16},{wch:30},{wch:40}];sheet['!autofilter']={ref:sheet['!ref']};XLSX.utils.book_append_sheet(wb,sheet,name);}XLSX.writeFile(wb,`모모네집_가계부_${period()}.xlsx`)}catch(e){$('notice').textContent=e.message}};
render();
