'use strict';
const META_STORAGE='momo-ledger-months-v2';let monthMeta={},revision=0,shared=typeof google!=='undefined'&&google.script&&google.script.run,busy=false;
try{monthMeta=JSON.parse(localStorage.getItem(META_STORAGE)||'{}')}catch{}
function statusFor(key){const m=monthMeta[key]||{};const owners=m.uploaded||[...new Set(records.filter(r=>r.date.startsWith(key)).map(r=>r.owner))];return {uploaded:owners,confirmed:Boolean(m.confirmed),updatedAt:m.updatedAt||''};}
function cloudCall(method,payload){return new Promise((resolve,reject)=>{const runner=google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(Error(e.message||String(e))));if(payload===undefined)runner[method]();else runner[method](payload)})}
function acceptState(state){records=validateRecords(state.records);monthMeta=state.months||{};revision=state.revision||0;}
function localMutation(op){let next=records.map(r=>({...r})),meta=JSON.parse(JSON.stringify(monthMeta));const ensure=k=>meta[k]??={...statusFor(k)};if(op.kind==='import'){if(!op.items?.length)throw Error('가져올 파일이 없어요.');const seen=new Set();for(const item of op.items){const key=item.period+'|'+item.owner;if(seen.has(key))throw Error('같은 월·입력자의 파일은 하나만 가져오세요.');seen.add(key);const imported=validateRecords(item.records);if(!imported.length||imported.some(r=>r.owner!==item.owner||r.date.slice(0,7)!==item.period))throw Error('파일과 연월·입력자가 일치하지 않아요.');const m=ensure(item.period);if(m.confirmed)throw Error(item.period+' 가계부는 확정되어 있어요. 먼저 확정을 해제하세요.');next=next.filter(r=>!(r.date.startsWith(item.period)&&r.owner===item.owner)).concat(imported);m.uploaded=[...new Set([...m.uploaded,item.owner])];m.confirmed=m.uploaded.includes('토끼')&&m.uploaded.includes('캥거루');m.updatedAt=new Date().toISOString();}}else if(op.kind==='edit'){const old=next.find(r=>r.id===op.record.id);if(!old)throw Error('수정할 내역이 없어요.');const key=old.date.slice(0,7);if(ensure(key).confirmed||ensure(op.record.date.slice(0,7)).confirmed)throw Error('확정한 달은 먼저 확정을 해제하세요.');next=next.map(r=>r.id===old.id?validateRecords([op.record])[0]:r);}else if(op.kind==='reopen'){ensure(op.period).confirmed=false;}else if(op.kind==='confirm'){const m=ensure(op.period);if(!['토끼','캥거루'].every(o=>m.uploaded.includes(o)))throw Error('두 사람의 업로드가 필요해요.');m.confirmed=true;}else if(op.kind==='restore'){next=validateRecords(op.records);meta=op.months||{};}else throw Error('지원하지 않는 저장 작업입니다.');const serialized=JSON.stringify({records:next,months:meta});localStorage.setItem('momo-ledger-state-v2',serialized);return {records:next,months:meta,revision:revision+1};}
async function mutate(op){if(busy)throw Error('저장 중이에요. 잠시 기다려 주세요.');busy=true;try{const state=shared?await cloudCall('mutateLedger',{...op,revision}):localMutation(op);acceptState(state);$('savedState').textContent=shared?'공동 저장됨':'이 브라우저에 저장됨';render();return state;}catch(e){if(shared){try{acceptState(await cloudCall('loadLedger'));render()}catch{}}throw e;}finally{busy=false}}
try{const state=JSON.parse(localStorage.getItem('momo-ledger-state-v2')||'null');if(state)acceptState(state)}catch{}
$('importForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{const items=[],form=e.target.elements;for(let i=0;i<pending.length;i++){const year=Number(form['year'+i].value),month=Number(form['month'+i].value),owner=form['owner'+i].value;items.push({period:year+'-'+String(month).padStart(2,'0'),owner,records:parseWorkbook(pending[i].wb,{owner,year,month})})}await mutate({kind:'import',items});const p=items[0].period.split('-');if(![...$('year').options].some(o=>o.value===p[0]))$('year').add(new Option(p[0]+'년',p[0]));$('year').value=p[0];$('month').value=Number(p[1]);$('notice').textContent=pending.map(p=>p.name).join(', ')+' · 저장했어요.';$('importDialog').close();render()}catch(err){alert(err.message)}finally{button.disabled=false}};
$('editForm').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target)),button=e.target.querySelector('[type=submit]');button.disabled=true;try{const r=validateRecords([{...editing,...values,amount:Number(values.amount)}])[0];await mutate({kind:'edit',record:r});$('editDialog').close();$('notice').textContent='수정한 내역을 저장했어요.'}catch(err){alert(err.message)}finally{button.disabled=false}};
$('save').onclick=async()=>{try{const m=statusFor(period());if(m.uploaded.length===2&&!m.confirmed){await mutate({kind:'confirm',period:period()});$('notice').textContent='이번 달 가계부를 다시 확정했어요.'}else if(shared){acceptState(await cloudCall('loadLedger'));render();$('notice').textContent='공동 저장된 최신 내용을 불러왔어요.'}else persist('내역은 자동 저장되어 있어요.')}catch(e){alert(e.message)}};
$('reopen').onclick=async()=>{if(!confirm('확정을 해제하고 이 달의 내역을 수정할까요?'))return;try{await mutate({kind:'reopen',period:period()});$('notice').textContent='확정을 해제했어요. 수정 후 저장을 누르면 다시 확정됩니다.'}catch(e){alert(e.message)}};
$('backup').onclick=()=>download(new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),records,months:monthMeta},null,2)],{type:'application/json'}),'모모네집_전체백업_'+new Date().toISOString().slice(0,10)+'.json');
$('backupFile').onchange=async()=>{try{if(shared)throw Error('공동 저장에서는 전체 교체 복원을 사용하지 않아요. 월별 파일을 가져와 주세요.');const file=$('backupFile').files[0];if(!file)return;const data=JSON.parse(await file.text());if(![1,2].includes(data.version))throw Error('가계부 백업 파일이 아닙니다.');const restored=validateRecords(data.records);if(!confirm(`백업 ${restored.length}건으로 전체 내역을 교체할까요?`))return;await mutate({kind:'restore',records:restored,months:data.months||{}});$('notice').textContent='백업을 복원했어요.'}catch(e){alert(e.message)}finally{$('backupFile').value=''}};
async function initShared(){if(!shared)return;$('notice').textContent='공동 가계부를 불러오는 중이에요…';for(const b of document.querySelectorAll('.actions button'))b.disabled=true;try{acceptState(await cloudCall('loadLedger'));$('storageFooter').textContent='두 사람의 내역이 Google Sheets에 함께 저장됩니다. 파일 가져오기와 수정은 자동 저장됩니다.';$('savedState').textContent='공동 저장 연결됨';$('notice').textContent='공동 가계부를 불러왔어요.';render();}catch(e){$('notice').textContent='공동 저장 연결 실패: '+e.message;return;}finally{if($('savedState').textContent==='공동 저장 연결됨')for(const b of document.querySelectorAll('.actions button'))b.disabled=false}}
